# A sample Gemfile
source "https://rubygems.org"

gem 'rjack-logback'
gem 'rspec'
gem 'rspec-mocks'
gem 'rspec-expectations'
gem 'pry'
gem 'settingslogic'
gem 'slop'
gem 'spoon'
gem 'consistent-hashing'
gem  'json'
gem 'state_machine'
gem 'descriptive_statistics'
gem 'guard-jruby-rspec'
