//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: config/combined_messages.proto
namespace com.game_machine.entity_system.generated
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrackExtra")]
  public partial class TrackExtra : global::ProtoBuf.IExtensible
  {
    public TrackExtra() {}
    
    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private float _velocity = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"velocity", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float velocity
    {
      get { return _velocity; }
      set { _velocity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Health")]
  public partial class Health : global::ProtoBuf.IExtensible
  {
    public Health() {}
    
    private int _health;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"health", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int health
    {
      get { return _health; }
      set { _health = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Effect")]
  public partial class Effect : global::ProtoBuf.IExtensible
  {
    public Effect() {}
    
    private int _length = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"length", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int length
    {
      get { return _length; }
      set { _length = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _healthDiff = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"healthDiff", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int healthDiff
    {
      get { return _healthDiff; }
      set { _healthDiff = value; }
    }
    private int _damageDiff = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"damageDiff", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int damageDiff
    {
      get { return _damageDiff; }
      set { _damageDiff = value; }
    }
    private int _timePeriod = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"timePeriod", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timePeriod
    {
      get { return _timePeriod; }
      set { _timePeriod = value; }
    }
    private string _type = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EffectList")]
  public partial class EffectList : global::ProtoBuf.IExtensible
  {
    public EffectList() {}
    
    private readonly global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Effect> _effect = new global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Effect>();
    [global::ProtoBuf.ProtoMember(1, Name=@"effect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Effect> effect
    {
      get { return _effect; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CombatAbility")]
  public partial class CombatAbility : global::ProtoBuf.IExtensible
  {
    public CombatAbility() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _hitChance = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hitChance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hitChance
    {
      get { return _hitChance; }
      set { _hitChance = value; }
    }
    private int _range;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"range", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int range
    {
      get { return _range; }
      set { _range = value; }
    }
    private string _type = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Attack")]
  public partial class Attack : global::ProtoBuf.IExtensible
  {
    public Attack() {}
    
    private string _attacker;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }
    private string _target;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string target
    {
      get { return _target; }
      set { _target = value; }
    }
    private int _combatAbilityId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"combatAbilityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int combatAbilityId
    {
      get { return _combatAbilityId; }
      set { _combatAbilityId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IsPlayer")]
  public partial class IsPlayer : global::ProtoBuf.IExtensible
  {
    public IsPlayer() {}
    
    private bool _enabled = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"enabled", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool enabled
    {
      get { return _enabled; }
      set { _enabled = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Rpc")]
  public partial class Rpc : global::ProtoBuf.IExtensible
  {
    public Rpc() {}
    
    private string _method;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string method
    {
      get { return _method; }
      set { _method = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _arguments = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"arguments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> arguments
    {
      get { return _arguments; }
    }
  
    private bool _returnValue = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"returnValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool returnValue
    {
      get { return _returnValue; }
      set { _returnValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageEnvelope")]
  public partial class MessageEnvelope : global::ProtoBuf.IExtensible
  {
    public MessageEnvelope() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _server = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"server", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string server
    {
      get { return _server; }
      set { _server = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrackEntity")]
  public partial class TrackEntity : global::ProtoBuf.IExtensible
  {
    public TrackEntity() {}
    
    private bool _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool value
    {
      get { return _value; }
      set { _value = value; }
    }
    private bool _internal = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"internal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool @internal
    {
      get { return _internal; }
      set { _internal = value; }
    }
    private com.game_machine.entity_system.generated.TrackExtra _trackExtra = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"trackExtra", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.TrackExtra trackExtra
    {
      get { return _trackExtra; }
      set { _trackExtra = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterPlayerObserver")]
  public partial class RegisterPlayerObserver : global::ProtoBuf.IExtensible
  {
    public RegisterPlayerObserver() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _event;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"event", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string @event
    {
      get { return _event; }
      set { _event = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRegister")]
  public partial class PlayerRegister : global::ProtoBuf.IExtensible
  {
    public PlayerRegister() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private com.game_machine.entity_system.generated.ClientConnection _clientConnection;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"clientConnection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.game_machine.entity_system.generated.ClientConnection clientConnection
    {
      get { return _clientConnection; }
      set { _clientConnection = value; }
    }
    private string _observer = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"observer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string observer
    {
      get { return _observer; }
      set { _observer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Disconnected")]
  public partial class Disconnected : global::ProtoBuf.IExtensible
  {
    public Disconnected() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _clientId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"clientId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string clientId
    {
      get { return _clientId; }
      set { _clientId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerLogout")]
  public partial class PlayerLogout : global::ProtoBuf.IExtensible
  {
    public PlayerLogout() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _authtoken = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"authtoken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string authtoken
    {
      get { return _authtoken; }
      set { _authtoken = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerAuthenticated")]
  public partial class PlayerAuthenticated : global::ProtoBuf.IExtensible
  {
    public PlayerAuthenticated() {}
    
    private string _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientDisconnect")]
  public partial class ClientDisconnect : global::ProtoBuf.IExtensible
  {
    public ClientDisconnect() {}
    
    private com.game_machine.entity_system.generated.ClientConnection _clientConnection;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientConnection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.game_machine.entity_system.generated.ClientConnection clientConnection
    {
      get { return _clientConnection; }
      set { _clientConnection = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ErrorMessage")]
  public partial class ErrorMessage : global::ProtoBuf.IExtensible
  {
    public ErrorMessage() {}
    
    private string _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatChannels")]
  public partial class ChatChannels : global::ProtoBuf.IExtensible
  {
    public ChatChannels() {}
    
    private readonly global::System.Collections.Generic.List<com.game_machine.entity_system.generated.ChatChannel> _chatChannel = new global::System.Collections.Generic.List<com.game_machine.entity_system.generated.ChatChannel>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chatChannel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.game_machine.entity_system.generated.ChatChannel> chatChannel
    {
      get { return _chatChannel; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatChannel")]
  public partial class ChatChannel : global::ProtoBuf.IExtensible
  {
    public ChatChannel() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private com.game_machine.entity_system.generated.Subscribers _subscribers = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"subscribers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Subscribers subscribers
    {
      get { return _subscribers; }
      set { _subscribers = value; }
    }
    private string _flags = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string flags
    {
      get { return _flags; }
      set { _flags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinChat")]
  public partial class JoinChat : global::ProtoBuf.IExtensible
  {
    public JoinChat() {}
    
    private readonly global::System.Collections.Generic.List<com.game_machine.entity_system.generated.ChatChannel> _chatChannel = new global::System.Collections.Generic.List<com.game_machine.entity_system.generated.ChatChannel>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chatChannel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.game_machine.entity_system.generated.ChatChannel> chatChannel
    {
      get { return _chatChannel; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LeaveChat")]
  public partial class LeaveChat : global::ProtoBuf.IExtensible
  {
    public LeaveChat() {}
    
    private readonly global::System.Collections.Generic.List<com.game_machine.entity_system.generated.ChatChannel> _chatChannel = new global::System.Collections.Generic.List<com.game_machine.entity_system.generated.ChatChannel>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chatChannel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.game_machine.entity_system.generated.ChatChannel> chatChannel
    {
      get { return _chatChannel; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatMessage")]
  public partial class ChatMessage : global::ProtoBuf.IExtensible
  {
    public ChatMessage() {}
    
    private com.game_machine.entity_system.generated.ChatChannel _chatChannel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chatChannel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.game_machine.entity_system.generated.ChatChannel chatChannel
    {
      get { return _chatChannel; }
      set { _chatChannel = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private string _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _senderId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"senderId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string senderId
    {
      get { return _senderId; }
      set { _senderId = value; }
    }
    private com.game_machine.entity_system.generated.Entity _entity = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"entity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Entity entity
    {
      get { return _entity; }
      set { _entity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatRegister")]
  public partial class ChatRegister : global::ProtoBuf.IExtensible
  {
    public ChatRegister() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatStatus")]
  public partial class ChatStatus : global::ProtoBuf.IExtensible
  {
    public ChatStatus() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Subscribers")]
  public partial class Subscribers : global::ProtoBuf.IExtensible
  {
    public Subscribers() {}
    
    private readonly global::System.Collections.Generic.List<string> _subscriberId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"subscriberId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> subscriberId
    {
      get { return _subscriberId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Subscribe")]
  public partial class Subscribe : global::ProtoBuf.IExtensible
  {
    public Subscribe() {}
    
    private string _topic = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"topic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string topic
    {
      get { return _topic; }
      set { _topic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Unsubscribe")]
  public partial class Unsubscribe : global::ProtoBuf.IExtensible
  {
    public Unsubscribe() {}
    
    private string _topic;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"topic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string topic
    {
      get { return _topic; }
      set { _topic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Publish")]
  public partial class Publish : global::ProtoBuf.IExtensible
  {
    public Publish() {}
    
    private string _topic = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"topic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string topic
    {
      get { return _topic; }
      set { _topic = value; }
    }
    private com.game_machine.entity_system.generated.Entity _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.game_machine.entity_system.generated.Entity message
    {
      get { return _message; }
      set { _message = value; }
    }
    private string _path = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectdbDel")]
  public partial class ObjectdbDel : global::ProtoBuf.IExtensible
  {
    public ObjectdbDel() {}
    
    private string _entityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"entityId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string entityId
    {
      get { return _entityId; }
      set { _entityId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectdbGet")]
  public partial class ObjectdbGet : global::ProtoBuf.IExtensible
  {
    public ObjectdbGet() {}
    
    private string _entityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"entityId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string entityId
    {
      get { return _entityId; }
      set { _entityId = value; }
    }
    private string _playerId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectdbGetResponse")]
  public partial class ObjectdbGetResponse : global::ProtoBuf.IExtensible
  {
    public ObjectdbGetResponse() {}
    
    private bool _entityFound;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"entityFound", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool entityFound
    {
      get { return _entityFound; }
      set { _entityFound = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectdbPut")]
  public partial class ObjectdbPut : global::ProtoBuf.IExtensible
  {
    public ObjectdbPut() {}
    
    private com.game_machine.entity_system.generated.Entity _entity;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"entity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.game_machine.entity_system.generated.Entity entity
    {
      get { return _entity; }
      set { _entity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectdbUpdate")]
  public partial class ObjectdbUpdate : global::ProtoBuf.IExtensible
  {
    public ObjectdbUpdate() {}
    
    private string _currentEntityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"currentEntityId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string currentEntityId
    {
      get { return _currentEntityId; }
      set { _currentEntityId = value; }
    }
    private string _updateClass = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"updateClass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string updateClass
    {
      get { return _updateClass; }
      set { _updateClass = value; }
    }
    private string _updateMethod;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"updateMethod", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string updateMethod
    {
      get { return _updateMethod; }
      set { _updateMethod = value; }
    }
    private com.game_machine.entity_system.generated.Entity _updateEntity;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"updateEntity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.game_machine.entity_system.generated.Entity updateEntity
    {
      get { return _updateEntity; }
      set { _updateEntity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientConnection")]
  public partial class ClientConnection : global::ProtoBuf.IExtensible
  {
    public ClientConnection() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _gateway = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gateway", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gateway
    {
      get { return _gateway; }
      set { _gateway = value; }
    }
    private string _server = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"server", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string server
    {
      get { return _server; }
      set { _server = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerLogin")]
  public partial class PlayerLogin : global::ProtoBuf.IExtensible
  {
    public PlayerLogin() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Name")]
  public partial class Name : global::ProtoBuf.IExtensible
  {
    public Name() {}
    
    private string _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IsNpc")]
  public partial class IsNpc : global::ProtoBuf.IExtensible
  {
    public IsNpc() {}
    
    private bool _enabled;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"enabled", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool enabled
    {
      get { return _enabled; }
      set { _enabled = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Player")]
  public partial class Player : global::ProtoBuf.IExtensible
  {
    public Player() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bool _authenticated = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"authenticated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool authenticated
    {
      get { return _authenticated; }
      set { _authenticated = value; }
    }
    private string _authtoken = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"authtoken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string authtoken
    {
      get { return _authtoken; }
      set { _authtoken = value; }
    }
    private com.game_machine.entity_system.generated.Transform _transform = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"transform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Transform transform
    {
      get { return _transform; }
      set { _transform = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3")]
  public partial class Vector3 : global::ProtoBuf.IExtensible
  {
    public Vector3() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private int _xi = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"xi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xi
    {
      get { return _xi; }
      set { _xi = value; }
    }
    private int _yi = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"yi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yi
    {
      get { return _yi; }
      set { _yi = value; }
    }
    private int _zi = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"zi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zi
    {
      get { return _zi; }
      set { _zi = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Quaternion")]
  public partial class Quaternion : global::ProtoBuf.IExtensible
  {
    public Quaternion() {}
    
    private float _w = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float w
    {
      get { return _w; }
      set { _w = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private int _wi = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int wi
    {
      get { return _wi; }
      set { _wi = value; }
    }
    private int _xi = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"xi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xi
    {
      get { return _xi; }
      set { _xi = value; }
    }
    private int _yi = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"yi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yi
    {
      get { return _yi; }
      set { _yi = value; }
    }
    private int _zi = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"zi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zi
    {
      get { return _zi; }
      set { _zi = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Transform")]
  public partial class Transform : global::ProtoBuf.IExtensible
  {
    public Transform() {}
    
    private com.game_machine.entity_system.generated.Vector3 _vector3 = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"vector3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Vector3 vector3
    {
      get { return _vector3; }
      set { _vector3 = value; }
    }
    private com.game_machine.entity_system.generated.Quaternion _quaternion = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"quaternion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Quaternion quaternion
    {
      get { return _quaternion; }
      set { _quaternion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EchoTest")]
  public partial class EchoTest : global::ProtoBuf.IExtensible
  {
    public EchoTest() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestObject")]
  public partial class TestObject : global::ProtoBuf.IExtensible
  {
    public TestObject() {}
    
    private string _optionalString = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"optionalString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string optionalString
    {
      get { return _optionalString; }
      set { _optionalString = value; }
    }
    private string _requiredString;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"requiredString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string requiredString
    {
      get { return _requiredString; }
      set { _requiredString = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _numbers = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"numbers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> numbers
    {
      get { return _numbers; }
    }
  
    private byte[] _bstring = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bstring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] bstring
    {
      get { return _bstring; }
      set { _bstring = value; }
    }
    private bool _bvalue = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bvalue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bvalue
    {
      get { return _bvalue; }
      set { _bvalue = value; }
    }
    private double _dvalue = default(double);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double dvalue
    {
      get { return _dvalue; }
      set { _dvalue = value; }
    }
    private float _fvalue = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fvalue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float fvalue
    {
      get { return _fvalue; }
      set { _fvalue = value; }
    }
    private long _numbers64 = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"numbers64", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long numbers64
    {
      get { return _numbers64; }
      set { _numbers64 = value; }
    }
    private readonly global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Player> _player = new global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Player>();
    [global::ProtoBuf.ProtoMember(9, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Player> player
    {
      get { return _player; }
    }
  
    private com.game_machine.entity_system.generated.TestObject.Corpus _corpus = com.game_machine.entity_system.generated.TestObject.Corpus.UNIVERSAL;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"corpus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.game_machine.entity_system.generated.TestObject.Corpus.UNIVERSAL)]
    public com.game_machine.entity_system.generated.TestObject.Corpus corpus
    {
      get { return _corpus; }
      set { _corpus = value; }
    }
    private readonly global::System.Collections.Generic.List<com.game_machine.entity_system.generated.TestObject.Corpus> _corpus2 = new global::System.Collections.Generic.List<com.game_machine.entity_system.generated.TestObject.Corpus>();
    [global::ProtoBuf.ProtoMember(11, Name=@"corpus2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<com.game_machine.entity_system.generated.TestObject.Corpus> corpus2
    {
      get { return _corpus2; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Corpus")]
    public enum Corpus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSAL", Value=0)]
      UNIVERSAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEB", Value=1)]
      WEB = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IMAGES", Value=2)]
      IMAGES = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCAL", Value=3)]
      LOCAL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEWS", Value=4)]
      NEWS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRODUCTS", Value=5)]
      PRODUCTS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VIDEO", Value=6)]
      VIDEO = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Neighbors")]
  public partial class Neighbors : global::ProtoBuf.IExtensible
  {
    public Neighbors() {}
    
    private readonly global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Entity> _entity = new global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Entity>();
    [global::ProtoBuf.ProtoMember(1, Name=@"entity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Entity> entity
    {
      get { return _entity; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetNeighbors")]
  public partial class GetNeighbors : global::ProtoBuf.IExtensible
  {
    public GetNeighbors() {}
    
    private uint _search_radius = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"search_radius", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint search_radius
    {
      get { return _search_radius; }
      set { _search_radius = value; }
    }
    private com.game_machine.entity_system.generated.Vector3 _vector3;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"vector3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.game_machine.entity_system.generated.Vector3 vector3
    {
      get { return _vector3; }
      set { _vector3 = value; }
    }
    private string _neighborType = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"neighborType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string neighborType
    {
      get { return _neighborType; }
      set { _neighborType = value; }
    }
    private string _gridName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gridName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gridName
    {
      get { return _gridName; }
      set { _gridName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageRouting")]
  public partial class MessageRouting : global::ProtoBuf.IExtensible
  {
    public MessageRouting() {}
    
    private string _destination = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"destination", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string destination
    {
      get { return _destination; }
      set { _destination = value; }
    }
    private string _senderId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"senderId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string senderId
    {
      get { return _senderId; }
      set { _senderId = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NativeBytes")]
  public partial class NativeBytes : global::ProtoBuf.IExtensible
  {
    public NativeBytes() {}
    
    private byte[] _bytes;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] bytes
    {
      get { return _bytes; }
      set { _bytes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JsonEntity")]
  public partial class JsonEntity : global::ProtoBuf.IExtensible
  {
    public JsonEntity() {}
    
    private string _json;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"json", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string json
    {
      get { return _json; }
      set { _json = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Entity")]
  public partial class Entity : global::ProtoBuf.IExtensible
  {
    public Entity() {}
    
    private com.game_machine.entity_system.generated.Player _player = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Player player
    {
      get { return _player; }
      set { _player = value; }
    }
    private com.game_machine.entity_system.generated.Neighbors _neighbors = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"neighbors", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Neighbors neighbors
    {
      get { return _neighbors; }
      set { _neighbors = value; }
    }
    private com.game_machine.entity_system.generated.MessageEnvelope _messageEnvelope = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"messageEnvelope", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.MessageEnvelope messageEnvelope
    {
      get { return _messageEnvelope; }
      set { _messageEnvelope = value; }
    }
    private com.game_machine.entity_system.generated.ChatMessage _chatMessage = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chatMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ChatMessage chatMessage
    {
      get { return _chatMessage; }
      set { _chatMessage = value; }
    }
    private com.game_machine.entity_system.generated.ClientConnection _clientConnection = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"clientConnection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ClientConnection clientConnection
    {
      get { return _clientConnection; }
      set { _clientConnection = value; }
    }
    private com.game_machine.entity_system.generated.EchoTest _echoTest = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"echoTest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.EchoTest echoTest
    {
      get { return _echoTest; }
      set { _echoTest = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private com.game_machine.entity_system.generated.PlayerLogin _playerLogin = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"playerLogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.PlayerLogin playerLogin
    {
      get { return _playerLogin; }
      set { _playerLogin = value; }
    }
    private com.game_machine.entity_system.generated.Subscribe _subscribe = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"subscribe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Subscribe subscribe
    {
      get { return _subscribe; }
      set { _subscribe = value; }
    }
    private com.game_machine.entity_system.generated.Publish _publish = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"publish", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Publish publish
    {
      get { return _publish; }
      set { _publish = value; }
    }
    private com.game_machine.entity_system.generated.ChatChannel _chatChannel = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"chatChannel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ChatChannel chatChannel
    {
      get { return _chatChannel; }
      set { _chatChannel = value; }
    }
    private com.game_machine.entity_system.generated.JoinChat _joinChat = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"joinChat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.JoinChat joinChat
    {
      get { return _joinChat; }
      set { _joinChat = value; }
    }
    private com.game_machine.entity_system.generated.LeaveChat _leaveChat = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"leaveChat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.LeaveChat leaveChat
    {
      get { return _leaveChat; }
      set { _leaveChat = value; }
    }
    private com.game_machine.entity_system.generated.Unsubscribe _unsubscribe = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"unsubscribe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Unsubscribe unsubscribe
    {
      get { return _unsubscribe; }
      set { _unsubscribe = value; }
    }
    private com.game_machine.entity_system.generated.ChatRegister _chatRegister = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"chatRegister", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ChatRegister chatRegister
    {
      get { return _chatRegister; }
      set { _chatRegister = value; }
    }
    private com.game_machine.entity_system.generated.ChatChannels _chatChannels = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"chatChannels", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ChatChannels chatChannels
    {
      get { return _chatChannels; }
      set { _chatChannels = value; }
    }
    private com.game_machine.entity_system.generated.ErrorMessage _errorMessage = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"errorMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ErrorMessage errorMessage
    {
      get { return _errorMessage; }
      set { _errorMessage = value; }
    }
    private com.game_machine.entity_system.generated.RegisterPlayerObserver _registerPlayerObserver = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"registerPlayerObserver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.RegisterPlayerObserver registerPlayerObserver
    {
      get { return _registerPlayerObserver; }
      set { _registerPlayerObserver = value; }
    }
    private com.game_machine.entity_system.generated.GetNeighbors _getNeighbors = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"getNeighbors", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.GetNeighbors getNeighbors
    {
      get { return _getNeighbors; }
      set { _getNeighbors = value; }
    }
    private com.game_machine.entity_system.generated.TrackEntity _trackEntity = null;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"trackEntity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.TrackEntity trackEntity
    {
      get { return _trackEntity; }
      set { _trackEntity = value; }
    }
    private com.game_machine.entity_system.generated.Transform _transform = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"transform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Transform transform
    {
      get { return _transform; }
      set { _transform = value; }
    }
    private com.game_machine.entity_system.generated.IsNpc _isNpc = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"isNpc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.IsNpc isNpc
    {
      get { return _isNpc; }
      set { _isNpc = value; }
    }
    private com.game_machine.entity_system.generated.Vector3 _vector3 = null;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"vector3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Vector3 vector3
    {
      get { return _vector3; }
      set { _vector3 = value; }
    }
    private com.game_machine.entity_system.generated.EntityList _entityList = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"entityList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.EntityList entityList
    {
      get { return _entityList; }
      set { _entityList = value; }
    }
    private bool _published = default(bool);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"published", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool published
    {
      get { return _published; }
      set { _published = value; }
    }
    private string _entityType = "";
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"entityType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string entityType
    {
      get { return _entityType; }
      set { _entityType = value; }
    }
    private com.game_machine.entity_system.generated.PlayerAuthenticated _playerAuthenticated = null;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"playerAuthenticated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.PlayerAuthenticated playerAuthenticated
    {
      get { return _playerAuthenticated; }
      set { _playerAuthenticated = value; }
    }
    private com.game_machine.entity_system.generated.PlayerLogout _playerLogout = null;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"playerLogout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.PlayerLogout playerLogout
    {
      get { return _playerLogout; }
      set { _playerLogout = value; }
    }
    private bool _sendToPlayer = default(bool);
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"sendToPlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool sendToPlayer
    {
      get { return _sendToPlayer; }
      set { _sendToPlayer = value; }
    }
    private com.game_machine.entity_system.generated.Rpc _rpc = null;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"rpc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Rpc rpc
    {
      get { return _rpc; }
      set { _rpc = value; }
    }
    private com.game_machine.entity_system.generated.Subscribers _subscribers = null;
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"subscribers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Subscribers subscribers
    {
      get { return _subscribers; }
      set { _subscribers = value; }
    }
    private bool _save = default(bool);
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"save", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool save
    {
      get { return _save; }
      set { _save = value; }
    }
    private com.game_machine.entity_system.generated.MessageRouting _messageRouting = null;
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"messageRouting", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.MessageRouting messageRouting
    {
      get { return _messageRouting; }
      set { _messageRouting = value; }
    }
    private com.game_machine.entity_system.generated.ObjectdbGetResponse _objectdbGetResponse = null;
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"objectdbGetResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ObjectdbGetResponse objectdbGetResponse
    {
      get { return _objectdbGetResponse; }
      set { _objectdbGetResponse = value; }
    }
    private com.game_machine.entity_system.generated.NativeBytes _nativeBytes = null;
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"nativeBytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.NativeBytes nativeBytes
    {
      get { return _nativeBytes; }
      set { _nativeBytes = value; }
    }
    private com.game_machine.entity_system.generated.ObjectdbGet _objectdbGet = null;
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"objectdbGet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ObjectdbGet objectdbGet
    {
      get { return _objectdbGet; }
      set { _objectdbGet = value; }
    }
    private com.game_machine.entity_system.generated.JsonEntity _jsonEntity = null;
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"jsonEntity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.JsonEntity jsonEntity
    {
      get { return _jsonEntity; }
      set { _jsonEntity = value; }
    }
    private string _destination = "";
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"destination", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string destination
    {
      get { return _destination; }
      set { _destination = value; }
    }
    private bool _json = default(bool);
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"json", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool json
    {
      get { return _json; }
      set { _json = value; }
    }
    private string _params = "";
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"params", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string @params
    {
      get { return _params; }
      set { _params = value; }
    }
    private com.game_machine.entity_system.generated.ChatStatus _chatStatus = null;
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"chatStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ChatStatus chatStatus
    {
      get { return _chatStatus; }
      set { _chatStatus = value; }
    }
    private com.game_machine.entity_system.generated.TrackExtra _trackExtra = null;
    [global::ProtoBuf.ProtoMember(1000, IsRequired = false, Name=@"trackExtra", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.TrackExtra trackExtra
    {
      get { return _trackExtra; }
      set { _trackExtra = value; }
    }
    private com.game_machine.entity_system.generated.Health _health = null;
    [global::ProtoBuf.ProtoMember(1001, IsRequired = false, Name=@"health", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Health health
    {
      get { return _health; }
      set { _health = value; }
    }
    private com.game_machine.entity_system.generated.Effect _effect = null;
    [global::ProtoBuf.ProtoMember(1002, IsRequired = false, Name=@"effect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Effect effect
    {
      get { return _effect; }
      set { _effect = value; }
    }
    private com.game_machine.entity_system.generated.EffectList _effectList = null;
    [global::ProtoBuf.ProtoMember(1003, IsRequired = false, Name=@"effectList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.EffectList effectList
    {
      get { return _effectList; }
      set { _effectList = value; }
    }
    private com.game_machine.entity_system.generated.CombatAbility _combatAbility = null;
    [global::ProtoBuf.ProtoMember(1004, IsRequired = false, Name=@"combatAbility", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.CombatAbility combatAbility
    {
      get { return _combatAbility; }
      set { _combatAbility = value; }
    }
    private com.game_machine.entity_system.generated.Attack _attack = null;
    [global::ProtoBuf.ProtoMember(1005, IsRequired = false, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Attack attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private com.game_machine.entity_system.generated.IsPlayer _isPlayer = null;
    [global::ProtoBuf.ProtoMember(1006, IsRequired = false, Name=@"isPlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.IsPlayer isPlayer
    {
      get { return _isPlayer; }
      set { _isPlayer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntityList")]
  public partial class EntityList : global::ProtoBuf.IExtensible
  {
    public EntityList() {}
    
    private readonly global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Entity> _entity = new global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Entity>();
    [global::ProtoBuf.ProtoMember(1, Name=@"entity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Entity> entity
    {
      get { return _entity; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientMessage")]
  public partial class ClientMessage : global::ProtoBuf.IExtensible
  {
    public ClientMessage() {}
    
    private readonly global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Entity> _entity = new global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Entity>();
    [global::ProtoBuf.ProtoMember(1, Name=@"entity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.game_machine.entity_system.generated.Entity> entity
    {
      get { return _entity; }
    }
  
    private com.game_machine.entity_system.generated.Player _player = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.Player player
    {
      get { return _player; }
      set { _player = value; }
    }
    private com.game_machine.entity_system.generated.PlayerLogin _playerLogin = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerLogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.PlayerLogin playerLogin
    {
      get { return _playerLogin; }
      set { _playerLogin = value; }
    }
    private com.game_machine.entity_system.generated.ClientConnection _clientConnection = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"clientConnection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ClientConnection clientConnection
    {
      get { return _clientConnection; }
      set { _clientConnection = value; }
    }
    private com.game_machine.entity_system.generated.ClientDisconnect _clientDisconnect = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"clientDisconnect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ClientDisconnect clientDisconnect
    {
      get { return _clientDisconnect; }
      set { _clientDisconnect = value; }
    }
    private com.game_machine.entity_system.generated.PlayerLogout _playerLogout = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"playerLogout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.PlayerLogout playerLogout
    {
      get { return _playerLogout; }
      set { _playerLogout = value; }
    }
    private com.game_machine.entity_system.generated.ErrorMessage _errorMessage = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"errorMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.game_machine.entity_system.generated.ErrorMessage errorMessage
    {
      get { return _errorMessage; }
      set { _errorMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}