require_relative 'default_handlers/team_handler'
require_relative 'default_handlers/zone_manager'
require_relative 'default_handlers/authentication/object_store'
require_relative 'default_handlers/authentication/player_register'