require_relative 'endpoints/tcp_handler'
require_relative 'endpoints/udt'
require_relative 'endpoints/udp'
require_relative 'endpoints/tcp'
require_relative 'endpoints/http/auth'
require_relative 'endpoints/http/rpc'
