
require_relative 'models/region'
require_relative 'models/player_status_update'
require_relative 'models/create_team'
require_relative 'models/destroy_team'
require_relative 'models/join_team'
require_relative 'models/team_accept_invite'
require_relative 'models/team_invite'
require_relative 'models/teams'
require_relative 'models/team'
require_relative 'models/teams_request'
require_relative 'models/team_joined'
require_relative 'models/leave_team'
require_relative 'models/player_team'
require_relative 'models/team_left'
require_relative 'models/echo_test'
require_relative 'models/find_match'
require_relative 'models/match'
