### Generated by rprotoc. DO NOT EDIT!
### <proto file: java/game_machine/src/main/resources/ClientMessage.proto>
# package com.game_machine.messages;
# 
# // protoc File.proto  --java_out= /src/main/java
# 
# 
# option optimize_for = SPEED;
# 
# 
# 
# message Msg {
#   required bytes body = 1;
#   optional int32 seq = 2;
#    
# }
# 

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Com
  module GameMachine
    module Messages
      ::Protobuf::OPTIONS[:"optimize_for"] = :SPEED
      class Msg < ::Protobuf::Message
        defined_in __FILE__
        required :bytes, :body, 1
        optional :int32, :seq, 2
      end
    end
  end
end