// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.game_machine.messages;

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage {
    // Use Msg.newBuilder() to construct.
    private Msg() {}
    
    private static final Msg defaultInstance = new Msg();
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }
    
    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_machine.messages.ClientMessage.internal_static_com_game_machine_messages_Msg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_machine.messages.ClientMessage.internal_static_com_game_machine_messages_Msg_fieldAccessorTable;
    }
    
    // required bytes body = 1;
    public static final int BODY_FIELD_NUMBER = 1;
    private boolean hasBody;
    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasBody() { return hasBody; }
    public com.google.protobuf.ByteString getBody() { return body_; }
    
    // optional int32 seq = 2;
    public static final int SEQ_FIELD_NUMBER = 2;
    private boolean hasSeq;
    private int seq_ = 0;
    public boolean hasSeq() { return hasSeq; }
    public int getSeq() { return seq_; }
    
    public final boolean isInitialized() {
      if (!hasBody) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasBody()) {
        output.writeBytes(1, getBody());
      }
      if (hasSeq()) {
        output.writeInt32(2, getSeq());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasBody()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBody());
      }
      if (hasSeq()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getSeq());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.game_machine.messages.ClientMessage.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.messages.ClientMessage.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.messages.ClientMessage.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.messages.ClientMessage.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.messages.ClientMessage.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.messages.ClientMessage.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.messages.ClientMessage.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.game_machine.messages.ClientMessage.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.messages.ClientMessage.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.messages.ClientMessage.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game_machine.messages.ClientMessage.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.game_machine.messages.ClientMessage.Msg result;
      
      // Construct using com.game_machine.messages.ClientMessage.Msg.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.game_machine.messages.ClientMessage.Msg();
        return builder;
      }
      
      protected com.game_machine.messages.ClientMessage.Msg internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.game_machine.messages.ClientMessage.Msg();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game_machine.messages.ClientMessage.Msg.getDescriptor();
      }
      
      public com.game_machine.messages.ClientMessage.Msg getDefaultInstanceForType() {
        return com.game_machine.messages.ClientMessage.Msg.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.game_machine.messages.ClientMessage.Msg build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.game_machine.messages.ClientMessage.Msg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.game_machine.messages.ClientMessage.Msg buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.game_machine.messages.ClientMessage.Msg returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game_machine.messages.ClientMessage.Msg) {
          return mergeFrom((com.game_machine.messages.ClientMessage.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game_machine.messages.ClientMessage.Msg other) {
        if (other == com.game_machine.messages.ClientMessage.Msg.getDefaultInstance()) return this;
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setBody(input.readBytes());
              break;
            }
            case 16: {
              setSeq(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required bytes body = 1;
      public boolean hasBody() {
        return result.hasBody();
      }
      public com.google.protobuf.ByteString getBody() {
        return result.getBody();
      }
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBody = true;
        result.body_ = value;
        return this;
      }
      public Builder clearBody() {
        result.hasBody = false;
        result.body_ = getDefaultInstance().getBody();
        return this;
      }
      
      // optional int32 seq = 2;
      public boolean hasSeq() {
        return result.hasSeq();
      }
      public int getSeq() {
        return result.getSeq();
      }
      public Builder setSeq(int value) {
        result.hasSeq = true;
        result.seq_ = value;
        return this;
      }
      public Builder clearSeq() {
        result.hasSeq = false;
        result.seq_ = 0;
        return this;
      }
    }
    
    static {
      com.game_machine.messages.ClientMessage.getDescriptor();
    }
    
    static {
      com.game_machine.messages.ClientMessage.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_machine_messages_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_machine_messages_Msg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8java/game_machine/src/main/resources/C" +
      "lientMessage.proto\022\031com.game_machine.mes" +
      "sages\" \n\003Msg\022\014\n\004body\030\001 \002(\014\022\013\n\003seq\030\002 \001(\005B" +
      "\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_game_machine_messages_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_game_machine_messages_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_machine_messages_Msg_descriptor,
              new java.lang.String[] { "Body", "Seq", },
              com.game_machine.messages.ClientMessage.Msg.class,
              com.game_machine.messages.ClientMessage.Msg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
