// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/messages.proto

package com.game_machine;

public final class Pb {
  private Pb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string key = 1;
    boolean hasKey();
    String getKey();
    
    // required string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class Item extends
      com.google.protobuf.GeneratedMessage
      implements ItemOrBuilder {
    // Use Item.newBuilder() to construct.
    private Item(Builder builder) {
      super(builder);
    }
    private Item(boolean noInit) {}
    
    private static final Item defaultInstance;
    public static Item getDefaultInstance() {
      return defaultInstance;
    }
    
    public Item getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_machine.Pb.internal_static_com_game_machine_Item_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_machine.Pb.internal_static_com_game_machine_Item_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game_machine.Pb.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game_machine.Pb.Item prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game_machine.Pb.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game_machine.Pb.internal_static_com_game_machine_Item_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game_machine.Pb.internal_static_com_game_machine_Item_fieldAccessorTable;
      }
      
      // Construct using com.game_machine.Pb.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game_machine.Pb.Item.getDescriptor();
      }
      
      public com.game_machine.Pb.Item getDefaultInstanceForType() {
        return com.game_machine.Pb.Item.getDefaultInstance();
      }
      
      public com.game_machine.Pb.Item build() {
        com.game_machine.Pb.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game_machine.Pb.Item buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game_machine.Pb.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game_machine.Pb.Item buildPartial() {
        com.game_machine.Pb.Item result = new com.game_machine.Pb.Item(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game_machine.Pb.Item) {
          return mergeFrom((com.game_machine.Pb.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game_machine.Pb.Item other) {
        if (other == com.game_machine.Pb.Item.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // required string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.game_machine.Item)
    }
    
    static {
      defaultInstance = new Item(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.game_machine.Item)
  }
  
  public interface GameCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // repeated .com.game_machine.Item items = 2;
    java.util.List<com.game_machine.Pb.Item> 
        getItemsList();
    com.game_machine.Pb.Item getItems(int index);
    int getItemsCount();
    java.util.List<? extends com.game_machine.Pb.ItemOrBuilder> 
        getItemsOrBuilderList();
    com.game_machine.Pb.ItemOrBuilder getItemsOrBuilder(
        int index);
  }
  public static final class GameCommand extends
      com.google.protobuf.GeneratedMessage
      implements GameCommandOrBuilder {
    // Use GameCommand.newBuilder() to construct.
    private GameCommand(Builder builder) {
      super(builder);
    }
    private GameCommand(boolean noInit) {}
    
    private static final GameCommand defaultInstance;
    public static GameCommand getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameCommand getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_machine.Pb.internal_static_com_game_machine_GameCommand_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_machine.Pb.internal_static_com_game_machine_GameCommand_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .com.game_machine.Item items = 2;
    public static final int ITEMS_FIELD_NUMBER = 2;
    private java.util.List<com.game_machine.Pb.Item> items_;
    public java.util.List<com.game_machine.Pb.Item> getItemsList() {
      return items_;
    }
    public java.util.List<? extends com.game_machine.Pb.ItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    public int getItemsCount() {
      return items_.size();
    }
    public com.game_machine.Pb.Item getItems(int index) {
      return items_.get(index);
    }
    public com.game_machine.Pb.ItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(2, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game_machine.Pb.GameCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.GameCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.GameCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game_machine.Pb.GameCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game_machine.Pb.GameCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game_machine.Pb.internal_static_com_game_machine_GameCommand_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game_machine.Pb.internal_static_com_game_machine_GameCommand_fieldAccessorTable;
      }
      
      // Construct using com.game_machine.Pb.GameCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game_machine.Pb.GameCommand.getDescriptor();
      }
      
      public com.game_machine.Pb.GameCommand getDefaultInstanceForType() {
        return com.game_machine.Pb.GameCommand.getDefaultInstance();
      }
      
      public com.game_machine.Pb.GameCommand build() {
        com.game_machine.Pb.GameCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game_machine.Pb.GameCommand buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game_machine.Pb.GameCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game_machine.Pb.GameCommand buildPartial() {
        com.game_machine.Pb.GameCommand result = new com.game_machine.Pb.GameCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game_machine.Pb.GameCommand) {
          return mergeFrom((com.game_machine.Pb.GameCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game_machine.Pb.GameCommand other) {
        if (other == com.game_machine.Pb.GameCommand.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              com.game_machine.Pb.Item.Builder subBuilder = com.game_machine.Pb.Item.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addItems(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // repeated .com.game_machine.Item items = 2;
      private java.util.List<com.game_machine.Pb.Item> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          items_ = new java.util.ArrayList<com.game_machine.Pb.Item>(items_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game_machine.Pb.Item, com.game_machine.Pb.Item.Builder, com.game_machine.Pb.ItemOrBuilder> itemsBuilder_;
      
      public java.util.List<com.game_machine.Pb.Item> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      public com.game_machine.Pb.Item getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      public Builder setItems(
          int index, com.game_machine.Pb.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setItems(
          int index, com.game_machine.Pb.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addItems(com.game_machine.Pb.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addItems(
          int index, com.game_machine.Pb.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addItems(
          com.game_machine.Pb.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addItems(
          int index, com.game_machine.Pb.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllItems(
          java.lang.Iterable<? extends com.game_machine.Pb.Item> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          super.addAll(values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      public com.game_machine.Pb.Item.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      public com.game_machine.Pb.ItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.game_machine.Pb.ItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      public com.game_machine.Pb.Item.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.game_machine.Pb.Item.getDefaultInstance());
      }
      public com.game_machine.Pb.Item.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.game_machine.Pb.Item.getDefaultInstance());
      }
      public java.util.List<com.game_machine.Pb.Item.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game_machine.Pb.Item, com.game_machine.Pb.Item.Builder, com.game_machine.Pb.ItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game_machine.Pb.Item, com.game_machine.Pb.Item.Builder, com.game_machine.Pb.ItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.game_machine.GameCommand)
    }
    
    static {
      defaultInstance = new GameCommand(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.game_machine.GameCommand)
  }
  
  public interface GameCommandsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.game_machine.GameCommand gameCommand = 1;
    java.util.List<com.game_machine.Pb.GameCommand> 
        getGameCommandList();
    com.game_machine.Pb.GameCommand getGameCommand(int index);
    int getGameCommandCount();
    java.util.List<? extends com.game_machine.Pb.GameCommandOrBuilder> 
        getGameCommandOrBuilderList();
    com.game_machine.Pb.GameCommandOrBuilder getGameCommandOrBuilder(
        int index);
  }
  public static final class GameCommands extends
      com.google.protobuf.GeneratedMessage
      implements GameCommandsOrBuilder {
    // Use GameCommands.newBuilder() to construct.
    private GameCommands(Builder builder) {
      super(builder);
    }
    private GameCommands(boolean noInit) {}
    
    private static final GameCommands defaultInstance;
    public static GameCommands getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameCommands getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_machine.Pb.internal_static_com_game_machine_GameCommands_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_machine.Pb.internal_static_com_game_machine_GameCommands_fieldAccessorTable;
    }
    
    // repeated .com.game_machine.GameCommand gameCommand = 1;
    public static final int GAMECOMMAND_FIELD_NUMBER = 1;
    private java.util.List<com.game_machine.Pb.GameCommand> gameCommand_;
    public java.util.List<com.game_machine.Pb.GameCommand> getGameCommandList() {
      return gameCommand_;
    }
    public java.util.List<? extends com.game_machine.Pb.GameCommandOrBuilder> 
        getGameCommandOrBuilderList() {
      return gameCommand_;
    }
    public int getGameCommandCount() {
      return gameCommand_.size();
    }
    public com.game_machine.Pb.GameCommand getGameCommand(int index) {
      return gameCommand_.get(index);
    }
    public com.game_machine.Pb.GameCommandOrBuilder getGameCommandOrBuilder(
        int index) {
      return gameCommand_.get(index);
    }
    
    private void initFields() {
      gameCommand_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getGameCommandCount(); i++) {
        if (!getGameCommand(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < gameCommand_.size(); i++) {
        output.writeMessage(1, gameCommand_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < gameCommand_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gameCommand_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game_machine.Pb.GameCommands parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.GameCommands parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.GameCommands parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.GameCommands parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.GameCommands parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.GameCommands parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.GameCommands parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.GameCommands parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.GameCommands parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.GameCommands parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game_machine.Pb.GameCommands prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game_machine.Pb.GameCommandsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game_machine.Pb.internal_static_com_game_machine_GameCommands_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game_machine.Pb.internal_static_com_game_machine_GameCommands_fieldAccessorTable;
      }
      
      // Construct using com.game_machine.Pb.GameCommands.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGameCommandFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (gameCommandBuilder_ == null) {
          gameCommand_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gameCommandBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game_machine.Pb.GameCommands.getDescriptor();
      }
      
      public com.game_machine.Pb.GameCommands getDefaultInstanceForType() {
        return com.game_machine.Pb.GameCommands.getDefaultInstance();
      }
      
      public com.game_machine.Pb.GameCommands build() {
        com.game_machine.Pb.GameCommands result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game_machine.Pb.GameCommands buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game_machine.Pb.GameCommands result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game_machine.Pb.GameCommands buildPartial() {
        com.game_machine.Pb.GameCommands result = new com.game_machine.Pb.GameCommands(this);
        int from_bitField0_ = bitField0_;
        if (gameCommandBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            gameCommand_ = java.util.Collections.unmodifiableList(gameCommand_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gameCommand_ = gameCommand_;
        } else {
          result.gameCommand_ = gameCommandBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game_machine.Pb.GameCommands) {
          return mergeFrom((com.game_machine.Pb.GameCommands)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game_machine.Pb.GameCommands other) {
        if (other == com.game_machine.Pb.GameCommands.getDefaultInstance()) return this;
        if (gameCommandBuilder_ == null) {
          if (!other.gameCommand_.isEmpty()) {
            if (gameCommand_.isEmpty()) {
              gameCommand_ = other.gameCommand_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGameCommandIsMutable();
              gameCommand_.addAll(other.gameCommand_);
            }
            onChanged();
          }
        } else {
          if (!other.gameCommand_.isEmpty()) {
            if (gameCommandBuilder_.isEmpty()) {
              gameCommandBuilder_.dispose();
              gameCommandBuilder_ = null;
              gameCommand_ = other.gameCommand_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gameCommandBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGameCommandFieldBuilder() : null;
            } else {
              gameCommandBuilder_.addAllMessages(other.gameCommand_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getGameCommandCount(); i++) {
          if (!getGameCommand(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.game_machine.Pb.GameCommand.Builder subBuilder = com.game_machine.Pb.GameCommand.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGameCommand(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.game_machine.GameCommand gameCommand = 1;
      private java.util.List<com.game_machine.Pb.GameCommand> gameCommand_ =
        java.util.Collections.emptyList();
      private void ensureGameCommandIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          gameCommand_ = new java.util.ArrayList<com.game_machine.Pb.GameCommand>(gameCommand_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game_machine.Pb.GameCommand, com.game_machine.Pb.GameCommand.Builder, com.game_machine.Pb.GameCommandOrBuilder> gameCommandBuilder_;
      
      public java.util.List<com.game_machine.Pb.GameCommand> getGameCommandList() {
        if (gameCommandBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gameCommand_);
        } else {
          return gameCommandBuilder_.getMessageList();
        }
      }
      public int getGameCommandCount() {
        if (gameCommandBuilder_ == null) {
          return gameCommand_.size();
        } else {
          return gameCommandBuilder_.getCount();
        }
      }
      public com.game_machine.Pb.GameCommand getGameCommand(int index) {
        if (gameCommandBuilder_ == null) {
          return gameCommand_.get(index);
        } else {
          return gameCommandBuilder_.getMessage(index);
        }
      }
      public Builder setGameCommand(
          int index, com.game_machine.Pb.GameCommand value) {
        if (gameCommandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameCommandIsMutable();
          gameCommand_.set(index, value);
          onChanged();
        } else {
          gameCommandBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGameCommand(
          int index, com.game_machine.Pb.GameCommand.Builder builderForValue) {
        if (gameCommandBuilder_ == null) {
          ensureGameCommandIsMutable();
          gameCommand_.set(index, builderForValue.build());
          onChanged();
        } else {
          gameCommandBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGameCommand(com.game_machine.Pb.GameCommand value) {
        if (gameCommandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameCommandIsMutable();
          gameCommand_.add(value);
          onChanged();
        } else {
          gameCommandBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGameCommand(
          int index, com.game_machine.Pb.GameCommand value) {
        if (gameCommandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameCommandIsMutable();
          gameCommand_.add(index, value);
          onChanged();
        } else {
          gameCommandBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGameCommand(
          com.game_machine.Pb.GameCommand.Builder builderForValue) {
        if (gameCommandBuilder_ == null) {
          ensureGameCommandIsMutable();
          gameCommand_.add(builderForValue.build());
          onChanged();
        } else {
          gameCommandBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGameCommand(
          int index, com.game_machine.Pb.GameCommand.Builder builderForValue) {
        if (gameCommandBuilder_ == null) {
          ensureGameCommandIsMutable();
          gameCommand_.add(index, builderForValue.build());
          onChanged();
        } else {
          gameCommandBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGameCommand(
          java.lang.Iterable<? extends com.game_machine.Pb.GameCommand> values) {
        if (gameCommandBuilder_ == null) {
          ensureGameCommandIsMutable();
          super.addAll(values, gameCommand_);
          onChanged();
        } else {
          gameCommandBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGameCommand() {
        if (gameCommandBuilder_ == null) {
          gameCommand_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gameCommandBuilder_.clear();
        }
        return this;
      }
      public Builder removeGameCommand(int index) {
        if (gameCommandBuilder_ == null) {
          ensureGameCommandIsMutable();
          gameCommand_.remove(index);
          onChanged();
        } else {
          gameCommandBuilder_.remove(index);
        }
        return this;
      }
      public com.game_machine.Pb.GameCommand.Builder getGameCommandBuilder(
          int index) {
        return getGameCommandFieldBuilder().getBuilder(index);
      }
      public com.game_machine.Pb.GameCommandOrBuilder getGameCommandOrBuilder(
          int index) {
        if (gameCommandBuilder_ == null) {
          return gameCommand_.get(index);  } else {
          return gameCommandBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.game_machine.Pb.GameCommandOrBuilder> 
           getGameCommandOrBuilderList() {
        if (gameCommandBuilder_ != null) {
          return gameCommandBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gameCommand_);
        }
      }
      public com.game_machine.Pb.GameCommand.Builder addGameCommandBuilder() {
        return getGameCommandFieldBuilder().addBuilder(
            com.game_machine.Pb.GameCommand.getDefaultInstance());
      }
      public com.game_machine.Pb.GameCommand.Builder addGameCommandBuilder(
          int index) {
        return getGameCommandFieldBuilder().addBuilder(
            index, com.game_machine.Pb.GameCommand.getDefaultInstance());
      }
      public java.util.List<com.game_machine.Pb.GameCommand.Builder> 
           getGameCommandBuilderList() {
        return getGameCommandFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game_machine.Pb.GameCommand, com.game_machine.Pb.GameCommand.Builder, com.game_machine.Pb.GameCommandOrBuilder> 
          getGameCommandFieldBuilder() {
        if (gameCommandBuilder_ == null) {
          gameCommandBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game_machine.Pb.GameCommand, com.game_machine.Pb.GameCommand.Builder, com.game_machine.Pb.GameCommandOrBuilder>(
                  gameCommand_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          gameCommand_ = null;
        }
        return gameCommandBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.game_machine.GameCommands)
    }
    
    static {
      defaultInstance = new GameCommands(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.game_machine.GameCommands)
  }
  
  public interface ClientMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes body = 1;
    boolean hasBody();
    com.google.protobuf.ByteString getBody();
    
    // required string playerId = 2;
    boolean hasPlayerId();
    String getPlayerId();
    
    // optional int64 timestamp = 3;
    boolean hasTimestamp();
    long getTimestamp();
    
    // optional int32 seq = 4;
    boolean hasSeq();
    int getSeq();
  }
  public static final class ClientMessage extends
      com.google.protobuf.GeneratedMessage
      implements ClientMessageOrBuilder {
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage(Builder builder) {
      super(builder);
    }
    private ClientMessage(boolean noInit) {}
    
    private static final ClientMessage defaultInstance;
    public static ClientMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_machine.Pb.internal_static_com_game_machine_ClientMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_machine.Pb.internal_static_com_game_machine_ClientMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes body = 1;
    public static final int BODY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString body_;
    public boolean hasBody() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    
    // required string playerId = 2;
    public static final int PLAYERID_FIELD_NUMBER = 2;
    private java.lang.Object playerId_;
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          playerId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // optional int32 seq = 4;
    public static final int SEQ_FIELD_NUMBER = 4;
    private int seq_;
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getSeq() {
      return seq_;
    }
    
    private void initFields() {
      body_ = com.google.protobuf.ByteString.EMPTY;
      playerId_ = "";
      timestamp_ = 0L;
      seq_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, body_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPlayerIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, seq_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, body_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPlayerIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, seq_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game_machine.Pb.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game_machine.Pb.ClientMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game_machine.Pb.ClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game_machine.Pb.internal_static_com_game_machine_ClientMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game_machine.Pb.internal_static_com_game_machine_ClientMessage_fieldAccessorTable;
      }
      
      // Construct using com.game_machine.Pb.ClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game_machine.Pb.ClientMessage.getDescriptor();
      }
      
      public com.game_machine.Pb.ClientMessage getDefaultInstanceForType() {
        return com.game_machine.Pb.ClientMessage.getDefaultInstance();
      }
      
      public com.game_machine.Pb.ClientMessage build() {
        com.game_machine.Pb.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game_machine.Pb.ClientMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game_machine.Pb.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game_machine.Pb.ClientMessage buildPartial() {
        com.game_machine.Pb.ClientMessage result = new com.game_machine.Pb.ClientMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.seq_ = seq_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game_machine.Pb.ClientMessage) {
          return mergeFrom((com.game_machine.Pb.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game_machine.Pb.ClientMessage other) {
        if (other == com.game_machine.Pb.ClientMessage.getDefaultInstance()) return this;
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasBody()) {
          
          return false;
        }
        if (!hasPlayerId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              body_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              playerId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              seq_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes body = 1;
      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBody() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        body_ = value;
        onChanged();
        return this;
      }
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      
      // required string playerId = 2;
      private java.lang.Object playerId_ = "";
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPlayerId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        playerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        playerId_ = getDefaultInstance().getPlayerId();
        onChanged();
        return this;
      }
      void setPlayerId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        playerId_ = value;
        onChanged();
      }
      
      // optional int64 timestamp = 3;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 seq = 4;
      private int seq_ ;
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getSeq() {
        return seq_;
      }
      public Builder setSeq(int value) {
        bitField0_ |= 0x00000008;
        seq_ = value;
        onChanged();
        return this;
      }
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000008);
        seq_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.game_machine.ClientMessage)
    }
    
    static {
      defaultInstance = new ClientMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.game_machine.ClientMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_machine_Item_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_machine_Item_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_machine_GameCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_machine_GameCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_machine_GameCommands_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_machine_GameCommands_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_machine_ClientMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_machine_ClientMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/resources/messages.proto\022\020com" +
      ".game_machine\"\"\n\004Item\022\013\n\003key\030\001 \002(\t\022\r\n\005va" +
      "lue\030\002 \002(\t\"B\n\013GameCommand\022\014\n\004name\030\001 \002(\t\022%" +
      "\n\005items\030\002 \003(\0132\026.com.game_machine.Item\"B\n" +
      "\014GameCommands\0222\n\013gameCommand\030\001 \003(\0132\035.com" +
      ".game_machine.GameCommand\"O\n\rClientMessa" +
      "ge\022\014\n\004body\030\001 \002(\014\022\020\n\010playerId\030\002 \002(\t\022\021\n\tti" +
      "mestamp\030\003 \001(\003\022\013\n\003seq\030\004 \001(\005B\006B\002PbH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_game_machine_Item_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_game_machine_Item_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_machine_Item_descriptor,
              new java.lang.String[] { "Key", "Value", },
              com.game_machine.Pb.Item.class,
              com.game_machine.Pb.Item.Builder.class);
          internal_static_com_game_machine_GameCommand_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_game_machine_GameCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_machine_GameCommand_descriptor,
              new java.lang.String[] { "Name", "Items", },
              com.game_machine.Pb.GameCommand.class,
              com.game_machine.Pb.GameCommand.Builder.class);
          internal_static_com_game_machine_GameCommands_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_game_machine_GameCommands_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_machine_GameCommands_descriptor,
              new java.lang.String[] { "GameCommand", },
              com.game_machine.Pb.GameCommands.class,
              com.game_machine.Pb.GameCommands.Builder.class);
          internal_static_com_game_machine_ClientMessage_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_game_machine_ClientMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_machine_ClientMessage_descriptor,
              new java.lang.String[] { "Body", "PlayerId", "Timestamp", "Seq", },
              com.game_machine.Pb.ClientMessage.class,
              com.game_machine.Pb.ClientMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
