// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/messages.proto

package com.game_machine;

public final class Pb {
  private Pb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 x = 1;
    boolean hasX();
    int getX();
    
    // optional int32 y = 2;
    boolean hasY();
    int getY();
    
    // optional int32 z = 3;
    boolean hasZ();
    int getZ();
    
    // required int32 id = 4;
    boolean hasId();
    int getId();
    
    // optional string name = 5;
    boolean hasName();
    String getName();
  }
  public static final class Player extends
      com.google.protobuf.GeneratedMessage
      implements PlayerOrBuilder {
    // Use Player.newBuilder() to construct.
    private Player(Builder builder) {
      super(builder);
    }
    private Player(boolean noInit) {}
    
    private static final Player defaultInstance;
    public static Player getDefaultInstance() {
      return defaultInstance;
    }
    
    public Player getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_machine.Pb.internal_static_com_game_machine_Player_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_machine.Pb.internal_static_com_game_machine_Player_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getX() {
      return x_;
    }
    
    // optional int32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getY() {
      return y_;
    }
    
    // optional int32 z = 3;
    public static final int Z_FIELD_NUMBER = 3;
    private int z_;
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getZ() {
      return z_;
    }
    
    // required int32 id = 4;
    public static final int ID_FIELD_NUMBER = 4;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getId() {
      return id_;
    }
    
    // optional string name = 5;
    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      x_ = 0;
      y_ = 0;
      z_ = 0;
      id_ = 0;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, z_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, id_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, z_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, id_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game_machine.Pb.Player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.Player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.Player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.Player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.Player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.Player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.Player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.Player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.Player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.Player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game_machine.Pb.Player prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game_machine.Pb.PlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game_machine.Pb.internal_static_com_game_machine_Player_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game_machine.Pb.internal_static_com_game_machine_Player_fieldAccessorTable;
      }
      
      // Construct using com.game_machine.Pb.Player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game_machine.Pb.Player.getDescriptor();
      }
      
      public com.game_machine.Pb.Player getDefaultInstanceForType() {
        return com.game_machine.Pb.Player.getDefaultInstance();
      }
      
      public com.game_machine.Pb.Player build() {
        com.game_machine.Pb.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game_machine.Pb.Player buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game_machine.Pb.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game_machine.Pb.Player buildPartial() {
        com.game_machine.Pb.Player result = new com.game_machine.Pb.Player(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game_machine.Pb.Player) {
          return mergeFrom((com.game_machine.Pb.Player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game_machine.Pb.Player other) {
        if (other == com.game_machine.Pb.Player.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              z_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              id_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 x = 1;
      private int x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getX() {
        return x_;
      }
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 y = 2;
      private int y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getY() {
        return y_;
      }
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 z = 3;
      private int z_ ;
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getZ() {
        return z_;
      }
      public Builder setZ(int value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 id = 4;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000008;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional string name = 5;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.game_machine.Player)
    }
    
    static {
      defaultInstance = new Player(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.game_machine.Player)
  }
  
  public interface ItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string key = 1;
    boolean hasKey();
    String getKey();
    
    // optional string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class Item extends
      com.google.protobuf.GeneratedMessage
      implements ItemOrBuilder {
    // Use Item.newBuilder() to construct.
    private Item(Builder builder) {
      super(builder);
    }
    private Item(boolean noInit) {}
    
    private static final Item defaultInstance;
    public static Item getDefaultInstance() {
      return defaultInstance;
    }
    
    public Item getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_machine.Pb.internal_static_com_game_machine_Item_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_machine.Pb.internal_static_com_game_machine_Item_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game_machine.Pb.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game_machine.Pb.Item prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game_machine.Pb.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game_machine.Pb.internal_static_com_game_machine_Item_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game_machine.Pb.internal_static_com_game_machine_Item_fieldAccessorTable;
      }
      
      // Construct using com.game_machine.Pb.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game_machine.Pb.Item.getDescriptor();
      }
      
      public com.game_machine.Pb.Item getDefaultInstanceForType() {
        return com.game_machine.Pb.Item.getDefaultInstance();
      }
      
      public com.game_machine.Pb.Item build() {
        com.game_machine.Pb.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game_machine.Pb.Item buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game_machine.Pb.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game_machine.Pb.Item buildPartial() {
        com.game_machine.Pb.Item result = new com.game_machine.Pb.Item(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game_machine.Pb.Item) {
          return mergeFrom((com.game_machine.Pb.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game_machine.Pb.Item other) {
        if (other == com.game_machine.Pb.Item.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // optional string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.game_machine.Item)
    }
    
    static {
      defaultInstance = new Item(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.game_machine.Item)
  }
  
  public interface GameCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // repeated .com.game_machine.Item item = 2;
    java.util.List<com.game_machine.Pb.Item> 
        getItemList();
    com.game_machine.Pb.Item getItem(int index);
    int getItemCount();
    java.util.List<? extends com.game_machine.Pb.ItemOrBuilder> 
        getItemOrBuilderList();
    com.game_machine.Pb.ItemOrBuilder getItemOrBuilder(
        int index);
  }
  public static final class GameCommand extends
      com.google.protobuf.GeneratedMessage
      implements GameCommandOrBuilder {
    // Use GameCommand.newBuilder() to construct.
    private GameCommand(Builder builder) {
      super(builder);
    }
    private GameCommand(boolean noInit) {}
    
    private static final GameCommand defaultInstance;
    public static GameCommand getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameCommand getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_machine.Pb.internal_static_com_game_machine_GameCommand_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_machine.Pb.internal_static_com_game_machine_GameCommand_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .com.game_machine.Item item = 2;
    public static final int ITEM_FIELD_NUMBER = 2;
    private java.util.List<com.game_machine.Pb.Item> item_;
    public java.util.List<com.game_machine.Pb.Item> getItemList() {
      return item_;
    }
    public java.util.List<? extends com.game_machine.Pb.ItemOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    public int getItemCount() {
      return item_.size();
    }
    public com.game_machine.Pb.Item getItem(int index) {
      return item_.get(index);
    }
    public com.game_machine.Pb.ItemOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      item_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemCount(); i++) {
        if (!getItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(2, item_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, item_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game_machine.Pb.GameCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.GameCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.GameCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.GameCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game_machine.Pb.GameCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game_machine.Pb.GameCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game_machine.Pb.internal_static_com_game_machine_GameCommand_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game_machine.Pb.internal_static_com_game_machine_GameCommand_fieldAccessorTable;
      }
      
      // Construct using com.game_machine.Pb.GameCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game_machine.Pb.GameCommand.getDescriptor();
      }
      
      public com.game_machine.Pb.GameCommand getDefaultInstanceForType() {
        return com.game_machine.Pb.GameCommand.getDefaultInstance();
      }
      
      public com.game_machine.Pb.GameCommand build() {
        com.game_machine.Pb.GameCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game_machine.Pb.GameCommand buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game_machine.Pb.GameCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game_machine.Pb.GameCommand buildPartial() {
        com.game_machine.Pb.GameCommand result = new com.game_machine.Pb.GameCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game_machine.Pb.GameCommand) {
          return mergeFrom((com.game_machine.Pb.GameCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game_machine.Pb.GameCommand other) {
        if (other == com.game_machine.Pb.GameCommand.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000002);
              itemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getItemCount(); i++) {
          if (!getItem(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              com.game_machine.Pb.Item.Builder subBuilder = com.game_machine.Pb.Item.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addItem(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // repeated .com.game_machine.Item item = 2;
      private java.util.List<com.game_machine.Pb.Item> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          item_ = new java.util.ArrayList<com.game_machine.Pb.Item>(item_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game_machine.Pb.Item, com.game_machine.Pb.Item.Builder, com.game_machine.Pb.ItemOrBuilder> itemBuilder_;
      
      public java.util.List<com.game_machine.Pb.Item> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      public com.game_machine.Pb.Item getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      public Builder setItem(
          int index, com.game_machine.Pb.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setItem(
          int index, com.game_machine.Pb.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addItem(com.game_machine.Pb.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addItem(
          int index, com.game_machine.Pb.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addItem(
          com.game_machine.Pb.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addItem(
          int index, com.game_machine.Pb.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllItem(
          java.lang.Iterable<? extends com.game_machine.Pb.Item> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          super.addAll(values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      public com.game_machine.Pb.Item.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      public com.game_machine.Pb.ItemOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.game_machine.Pb.ItemOrBuilder> 
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      public com.game_machine.Pb.Item.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            com.game_machine.Pb.Item.getDefaultInstance());
      }
      public com.game_machine.Pb.Item.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, com.game_machine.Pb.Item.getDefaultInstance());
      }
      public java.util.List<com.game_machine.Pb.Item.Builder> 
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game_machine.Pb.Item, com.game_machine.Pb.Item.Builder, com.game_machine.Pb.ItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game_machine.Pb.Item, com.game_machine.Pb.Item.Builder, com.game_machine.Pb.ItemOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.game_machine.GameCommand)
    }
    
    static {
      defaultInstance = new GameCommand(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.game_machine.GameCommand)
  }
  
  public interface ClientMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes data = 1;
    boolean hasData();
    com.google.protobuf.ByteString getData();
    
    // repeated .com.game_machine.Player players = 2;
    java.util.List<com.game_machine.Pb.Player> 
        getPlayersList();
    com.game_machine.Pb.Player getPlayers(int index);
    int getPlayersCount();
    java.util.List<? extends com.game_machine.Pb.PlayerOrBuilder> 
        getPlayersOrBuilderList();
    com.game_machine.Pb.PlayerOrBuilder getPlayersOrBuilder(
        int index);
    
    // repeated .com.game_machine.GameCommand gameCommands = 3;
    java.util.List<com.game_machine.Pb.GameCommand> 
        getGameCommandsList();
    com.game_machine.Pb.GameCommand getGameCommands(int index);
    int getGameCommandsCount();
    java.util.List<? extends com.game_machine.Pb.GameCommandOrBuilder> 
        getGameCommandsOrBuilderList();
    com.game_machine.Pb.GameCommandOrBuilder getGameCommandsOrBuilder(
        int index);
  }
  public static final class ClientMessage extends
      com.google.protobuf.GeneratedMessage
      implements ClientMessageOrBuilder {
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage(Builder builder) {
      super(builder);
    }
    private ClientMessage(boolean noInit) {}
    
    private static final ClientMessage defaultInstance;
    public static ClientMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game_machine.Pb.internal_static_com_game_machine_ClientMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game_machine.Pb.internal_static_com_game_machine_ClientMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    // repeated .com.game_machine.Player players = 2;
    public static final int PLAYERS_FIELD_NUMBER = 2;
    private java.util.List<com.game_machine.Pb.Player> players_;
    public java.util.List<com.game_machine.Pb.Player> getPlayersList() {
      return players_;
    }
    public java.util.List<? extends com.game_machine.Pb.PlayerOrBuilder> 
        getPlayersOrBuilderList() {
      return players_;
    }
    public int getPlayersCount() {
      return players_.size();
    }
    public com.game_machine.Pb.Player getPlayers(int index) {
      return players_.get(index);
    }
    public com.game_machine.Pb.PlayerOrBuilder getPlayersOrBuilder(
        int index) {
      return players_.get(index);
    }
    
    // repeated .com.game_machine.GameCommand gameCommands = 3;
    public static final int GAMECOMMANDS_FIELD_NUMBER = 3;
    private java.util.List<com.game_machine.Pb.GameCommand> gameCommands_;
    public java.util.List<com.game_machine.Pb.GameCommand> getGameCommandsList() {
      return gameCommands_;
    }
    public java.util.List<? extends com.game_machine.Pb.GameCommandOrBuilder> 
        getGameCommandsOrBuilderList() {
      return gameCommands_;
    }
    public int getGameCommandsCount() {
      return gameCommands_.size();
    }
    public com.game_machine.Pb.GameCommand getGameCommands(int index) {
      return gameCommands_.get(index);
    }
    public com.game_machine.Pb.GameCommandOrBuilder getGameCommandsOrBuilder(
        int index) {
      return gameCommands_.get(index);
    }
    
    private void initFields() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      players_ = java.util.Collections.emptyList();
      gameCommands_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPlayersCount(); i++) {
        if (!getPlayers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getGameCommandsCount(); i++) {
        if (!getGameCommands(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, data_);
      }
      for (int i = 0; i < players_.size(); i++) {
        output.writeMessage(2, players_.get(i));
      }
      for (int i = 0; i < gameCommands_.size(); i++) {
        output.writeMessage(3, gameCommands_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      for (int i = 0; i < players_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, players_.get(i));
      }
      for (int i = 0; i < gameCommands_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, gameCommands_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game_machine.Pb.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game_machine.Pb.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game_machine.Pb.ClientMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game_machine.Pb.ClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game_machine.Pb.internal_static_com_game_machine_ClientMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game_machine.Pb.internal_static_com_game_machine_ClientMessage_fieldAccessorTable;
      }
      
      // Construct using com.game_machine.Pb.ClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayersFieldBuilder();
          getGameCommandsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          playersBuilder_.clear();
        }
        if (gameCommandsBuilder_ == null) {
          gameCommands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          gameCommandsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game_machine.Pb.ClientMessage.getDescriptor();
      }
      
      public com.game_machine.Pb.ClientMessage getDefaultInstanceForType() {
        return com.game_machine.Pb.ClientMessage.getDefaultInstance();
      }
      
      public com.game_machine.Pb.ClientMessage build() {
        com.game_machine.Pb.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game_machine.Pb.ClientMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game_machine.Pb.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game_machine.Pb.ClientMessage buildPartial() {
        com.game_machine.Pb.ClientMessage result = new com.game_machine.Pb.ClientMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        if (playersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            players_ = java.util.Collections.unmodifiableList(players_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.players_ = players_;
        } else {
          result.players_ = playersBuilder_.build();
        }
        if (gameCommandsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            gameCommands_ = java.util.Collections.unmodifiableList(gameCommands_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.gameCommands_ = gameCommands_;
        } else {
          result.gameCommands_ = gameCommandsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game_machine.Pb.ClientMessage) {
          return mergeFrom((com.game_machine.Pb.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game_machine.Pb.ClientMessage other) {
        if (other == com.game_machine.Pb.ClientMessage.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        if (playersBuilder_ == null) {
          if (!other.players_.isEmpty()) {
            if (players_.isEmpty()) {
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePlayersIsMutable();
              players_.addAll(other.players_);
            }
            onChanged();
          }
        } else {
          if (!other.players_.isEmpty()) {
            if (playersBuilder_.isEmpty()) {
              playersBuilder_.dispose();
              playersBuilder_ = null;
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000002);
              playersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPlayersFieldBuilder() : null;
            } else {
              playersBuilder_.addAllMessages(other.players_);
            }
          }
        }
        if (gameCommandsBuilder_ == null) {
          if (!other.gameCommands_.isEmpty()) {
            if (gameCommands_.isEmpty()) {
              gameCommands_ = other.gameCommands_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureGameCommandsIsMutable();
              gameCommands_.addAll(other.gameCommands_);
            }
            onChanged();
          }
        } else {
          if (!other.gameCommands_.isEmpty()) {
            if (gameCommandsBuilder_.isEmpty()) {
              gameCommandsBuilder_.dispose();
              gameCommandsBuilder_ = null;
              gameCommands_ = other.gameCommands_;
              bitField0_ = (bitField0_ & ~0x00000004);
              gameCommandsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGameCommandsFieldBuilder() : null;
            } else {
              gameCommandsBuilder_.addAllMessages(other.gameCommands_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPlayersCount(); i++) {
          if (!getPlayers(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getGameCommandsCount(); i++) {
          if (!getGameCommands(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
            case 18: {
              com.game_machine.Pb.Player.Builder subBuilder = com.game_machine.Pb.Player.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPlayers(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.game_machine.Pb.GameCommand.Builder subBuilder = com.game_machine.Pb.GameCommand.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGameCommands(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes data = 1;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // repeated .com.game_machine.Player players = 2;
      private java.util.List<com.game_machine.Pb.Player> players_ =
        java.util.Collections.emptyList();
      private void ensurePlayersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          players_ = new java.util.ArrayList<com.game_machine.Pb.Player>(players_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game_machine.Pb.Player, com.game_machine.Pb.Player.Builder, com.game_machine.Pb.PlayerOrBuilder> playersBuilder_;
      
      public java.util.List<com.game_machine.Pb.Player> getPlayersList() {
        if (playersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(players_);
        } else {
          return playersBuilder_.getMessageList();
        }
      }
      public int getPlayersCount() {
        if (playersBuilder_ == null) {
          return players_.size();
        } else {
          return playersBuilder_.getCount();
        }
      }
      public com.game_machine.Pb.Player getPlayers(int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);
        } else {
          return playersBuilder_.getMessage(index);
        }
      }
      public Builder setPlayers(
          int index, com.game_machine.Pb.Player value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.set(index, value);
          onChanged();
        } else {
          playersBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPlayers(
          int index, com.game_machine.Pb.Player.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.set(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPlayers(com.game_machine.Pb.Player value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(value);
          onChanged();
        } else {
          playersBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPlayers(
          int index, com.game_machine.Pb.Player value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(index, value);
          onChanged();
        } else {
          playersBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPlayers(
          com.game_machine.Pb.Player.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPlayers(
          int index, com.game_machine.Pb.Player.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPlayers(
          java.lang.Iterable<? extends com.game_machine.Pb.Player> values) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          super.addAll(values, players_);
          onChanged();
        } else {
          playersBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPlayers() {
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          playersBuilder_.clear();
        }
        return this;
      }
      public Builder removePlayers(int index) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.remove(index);
          onChanged();
        } else {
          playersBuilder_.remove(index);
        }
        return this;
      }
      public com.game_machine.Pb.Player.Builder getPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().getBuilder(index);
      }
      public com.game_machine.Pb.PlayerOrBuilder getPlayersOrBuilder(
          int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);  } else {
          return playersBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.game_machine.Pb.PlayerOrBuilder> 
           getPlayersOrBuilderList() {
        if (playersBuilder_ != null) {
          return playersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(players_);
        }
      }
      public com.game_machine.Pb.Player.Builder addPlayersBuilder() {
        return getPlayersFieldBuilder().addBuilder(
            com.game_machine.Pb.Player.getDefaultInstance());
      }
      public com.game_machine.Pb.Player.Builder addPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().addBuilder(
            index, com.game_machine.Pb.Player.getDefaultInstance());
      }
      public java.util.List<com.game_machine.Pb.Player.Builder> 
           getPlayersBuilderList() {
        return getPlayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game_machine.Pb.Player, com.game_machine.Pb.Player.Builder, com.game_machine.Pb.PlayerOrBuilder> 
          getPlayersFieldBuilder() {
        if (playersBuilder_ == null) {
          playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game_machine.Pb.Player, com.game_machine.Pb.Player.Builder, com.game_machine.Pb.PlayerOrBuilder>(
                  players_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          players_ = null;
        }
        return playersBuilder_;
      }
      
      // repeated .com.game_machine.GameCommand gameCommands = 3;
      private java.util.List<com.game_machine.Pb.GameCommand> gameCommands_ =
        java.util.Collections.emptyList();
      private void ensureGameCommandsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          gameCommands_ = new java.util.ArrayList<com.game_machine.Pb.GameCommand>(gameCommands_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game_machine.Pb.GameCommand, com.game_machine.Pb.GameCommand.Builder, com.game_machine.Pb.GameCommandOrBuilder> gameCommandsBuilder_;
      
      public java.util.List<com.game_machine.Pb.GameCommand> getGameCommandsList() {
        if (gameCommandsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gameCommands_);
        } else {
          return gameCommandsBuilder_.getMessageList();
        }
      }
      public int getGameCommandsCount() {
        if (gameCommandsBuilder_ == null) {
          return gameCommands_.size();
        } else {
          return gameCommandsBuilder_.getCount();
        }
      }
      public com.game_machine.Pb.GameCommand getGameCommands(int index) {
        if (gameCommandsBuilder_ == null) {
          return gameCommands_.get(index);
        } else {
          return gameCommandsBuilder_.getMessage(index);
        }
      }
      public Builder setGameCommands(
          int index, com.game_machine.Pb.GameCommand value) {
        if (gameCommandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameCommandsIsMutable();
          gameCommands_.set(index, value);
          onChanged();
        } else {
          gameCommandsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGameCommands(
          int index, com.game_machine.Pb.GameCommand.Builder builderForValue) {
        if (gameCommandsBuilder_ == null) {
          ensureGameCommandsIsMutable();
          gameCommands_.set(index, builderForValue.build());
          onChanged();
        } else {
          gameCommandsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGameCommands(com.game_machine.Pb.GameCommand value) {
        if (gameCommandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameCommandsIsMutable();
          gameCommands_.add(value);
          onChanged();
        } else {
          gameCommandsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGameCommands(
          int index, com.game_machine.Pb.GameCommand value) {
        if (gameCommandsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameCommandsIsMutable();
          gameCommands_.add(index, value);
          onChanged();
        } else {
          gameCommandsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGameCommands(
          com.game_machine.Pb.GameCommand.Builder builderForValue) {
        if (gameCommandsBuilder_ == null) {
          ensureGameCommandsIsMutable();
          gameCommands_.add(builderForValue.build());
          onChanged();
        } else {
          gameCommandsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGameCommands(
          int index, com.game_machine.Pb.GameCommand.Builder builderForValue) {
        if (gameCommandsBuilder_ == null) {
          ensureGameCommandsIsMutable();
          gameCommands_.add(index, builderForValue.build());
          onChanged();
        } else {
          gameCommandsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGameCommands(
          java.lang.Iterable<? extends com.game_machine.Pb.GameCommand> values) {
        if (gameCommandsBuilder_ == null) {
          ensureGameCommandsIsMutable();
          super.addAll(values, gameCommands_);
          onChanged();
        } else {
          gameCommandsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGameCommands() {
        if (gameCommandsBuilder_ == null) {
          gameCommands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          gameCommandsBuilder_.clear();
        }
        return this;
      }
      public Builder removeGameCommands(int index) {
        if (gameCommandsBuilder_ == null) {
          ensureGameCommandsIsMutable();
          gameCommands_.remove(index);
          onChanged();
        } else {
          gameCommandsBuilder_.remove(index);
        }
        return this;
      }
      public com.game_machine.Pb.GameCommand.Builder getGameCommandsBuilder(
          int index) {
        return getGameCommandsFieldBuilder().getBuilder(index);
      }
      public com.game_machine.Pb.GameCommandOrBuilder getGameCommandsOrBuilder(
          int index) {
        if (gameCommandsBuilder_ == null) {
          return gameCommands_.get(index);  } else {
          return gameCommandsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.game_machine.Pb.GameCommandOrBuilder> 
           getGameCommandsOrBuilderList() {
        if (gameCommandsBuilder_ != null) {
          return gameCommandsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gameCommands_);
        }
      }
      public com.game_machine.Pb.GameCommand.Builder addGameCommandsBuilder() {
        return getGameCommandsFieldBuilder().addBuilder(
            com.game_machine.Pb.GameCommand.getDefaultInstance());
      }
      public com.game_machine.Pb.GameCommand.Builder addGameCommandsBuilder(
          int index) {
        return getGameCommandsFieldBuilder().addBuilder(
            index, com.game_machine.Pb.GameCommand.getDefaultInstance());
      }
      public java.util.List<com.game_machine.Pb.GameCommand.Builder> 
           getGameCommandsBuilderList() {
        return getGameCommandsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.game_machine.Pb.GameCommand, com.game_machine.Pb.GameCommand.Builder, com.game_machine.Pb.GameCommandOrBuilder> 
          getGameCommandsFieldBuilder() {
        if (gameCommandsBuilder_ == null) {
          gameCommandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.game_machine.Pb.GameCommand, com.game_machine.Pb.GameCommand.Builder, com.game_machine.Pb.GameCommandOrBuilder>(
                  gameCommands_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          gameCommands_ = null;
        }
        return gameCommandsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.game_machine.ClientMessage)
    }
    
    static {
      defaultInstance = new ClientMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.game_machine.ClientMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_machine_Player_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_machine_Player_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_machine_Item_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_machine_Item_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_machine_GameCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_machine_GameCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_machine_ClientMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_machine_ClientMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/resources/messages.proto\022\020com" +
      ".game_machine\"C\n\006Player\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030" +
      "\002 \001(\005\022\t\n\001z\030\003 \001(\005\022\n\n\002id\030\004 \002(\005\022\014\n\004name\030\005 \001" +
      "(\t\"\"\n\004Item\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \001(\t\"A" +
      "\n\013GameCommand\022\014\n\004name\030\001 \002(\t\022$\n\004item\030\002 \003(" +
      "\0132\026.com.game_machine.Item\"}\n\rClientMessa" +
      "ge\022\014\n\004data\030\001 \001(\014\022)\n\007players\030\002 \003(\0132\030.com." +
      "game_machine.Player\0223\n\014gameCommands\030\003 \003(" +
      "\0132\035.com.game_machine.GameCommandB\006B\002PbH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_game_machine_Player_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_game_machine_Player_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_machine_Player_descriptor,
              new java.lang.String[] { "X", "Y", "Z", "Id", "Name", },
              com.game_machine.Pb.Player.class,
              com.game_machine.Pb.Player.Builder.class);
          internal_static_com_game_machine_Item_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_game_machine_Item_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_machine_Item_descriptor,
              new java.lang.String[] { "Key", "Value", },
              com.game_machine.Pb.Item.class,
              com.game_machine.Pb.Item.Builder.class);
          internal_static_com_game_machine_GameCommand_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_game_machine_GameCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_machine_GameCommand_descriptor,
              new java.lang.String[] { "Name", "Item", },
              com.game_machine.Pb.GameCommand.class,
              com.game_machine.Pb.GameCommand.Builder.class);
          internal_static_com_game_machine_ClientMessage_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_game_machine_ClientMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_machine_ClientMessage_descriptor,
              new java.lang.String[] { "Data", "Players", "GameCommands", },
              com.game_machine.Pb.ClientMessage.class,
              com.game_machine.Pb.ClientMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
